import "./globals.css";
import type { Metadata } from "next";
import { Dela_Gothic_One, Instrument_Sans } from "next/font/google";
const dela = Dela_Gothic_One({ weight: "400", subsets: ["latin"] });
const sans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>{children}</body>
    </html>
  );
}
